// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8d1MCZSJGtWuHAfM5xljHFuAOgpvb-pI',
    appId: '1:547169101405:web:412fc4ffa08e7a3ff94fb4',
    messagingSenderId: '547169101405',
    projectId: 'isl-to-text-13',
    authDomain: 'isl-to-text-13.firebaseapp.com',
    storageBucket: 'isl-to-text-13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU6anbSb5KAiswsLeL2RSrycnRbH_wkfs',
    appId: '1:547169101405:android:e1003ba9702ff557f94fb4',
    messagingSenderId: '547169101405',
    projectId: 'isl-to-text-13',
    storageBucket: 'isl-to-text-13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM8z9prciY90zo-ISAKTlw128VyrUdzJI',
    appId: '1:547169101405:ios:62b70c5066b4a46df94fb4',
    messagingSenderId: '547169101405',
    projectId: 'isl-to-text-13',
    storageBucket: 'isl-to-text-13.firebasestorage.app',
    iosBundleId: 'com.example.signScribe2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM8z9prciY90zo-ISAKTlw128VyrUdzJI',
    appId: '1:547169101405:ios:62b70c5066b4a46df94fb4',
    messagingSenderId: '547169101405',
    projectId: 'isl-to-text-13',
    storageBucket: 'isl-to-text-13.firebasestorage.app',
    iosBundleId: 'com.example.signScribe2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8d1MCZSJGtWuHAfM5xljHFuAOgpvb-pI',
    appId: '1:547169101405:web:f55bea67c309d767f94fb4',
    messagingSenderId: '547169101405',
    projectId: 'isl-to-text-13',
    authDomain: 'isl-to-text-13.firebaseapp.com',
    storageBucket: 'isl-to-text-13.firebasestorage.app',
  );
}
